### ISSUE TITLE
Error volume declared as external

### ISSUE THREAD

**Issue by eastuger** [organization-supply/organization.supply#61]
**Describe the bug**
The run description is off. Readme states that docker-compose build & up will suffice for running this application. But it doesn't run . 

Returns this error message:  

`Creating network "organizationsupply_default" with the default driver
ERROR: Volume inventory declared as external, but could not be found. Please create the volume manually using `docker volume create --name=inventory` and try again.
`

**To Reproduce**
Steps to reproduce the behavior (eg:)
1. docker-compose build 
2. docker-compose up 

**Expected behavior**
Add to readme that a manual creation of the volume is necessary to run this project 

**Screenshots**

**Environment (please complete the following information):**
 - Device: Laptop
 - OS: Linux manjaro 19.02
 - N/A
 - N/A

**Additional context**
Happened on fresh clone and fresh build

**Comment by jplattel** [comment]
Running `docker volume create --name=inventory` should solve this. Adding it to the README :)
